package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentImgId generated by hbm2java
 */
@Embeddable
public class CommentImgId implements java.io.Serializable {

	private int comment;
	private int img;

	public CommentImgId() {
	}

	public CommentImgId(int comment, int img) {
		this.comment = comment;
		this.img = img;
	}

	@Column(name = "comment", nullable = false)
	public int getComment() {
		return this.comment;
	}

	public void setComment(int comment) {
		this.comment = comment;
	}

	@Column(name = "img", nullable = false)
	public int getImg() {
		return this.img;
	}

	public void setImg(int img) {
		this.img = img;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentImgId))
			return false;
		CommentImgId castOther = (CommentImgId) other;

		return (this.getComment() == castOther.getComment())
				&& (this.getImg() == castOther.getImg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getComment();
		result = 37 * result + this.getImg();
		return result;
	}

}
