package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "Comment", catalog = "villa")
public class Comment implements java.io.Serializable {

	private Integer id;
	private Integer member;
	private Integer villa;
	private Integer order;
	private Integer star;
	private String content;
	private Date time;

	public Comment() {
	}

	public Comment(Integer member, Integer villa, Integer order, Integer star,
			String content, Date time) {
		this.member = member;
		this.villa = villa;
		this.order = order;
		this.star = star;
		this.content = content;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "member")
	public Integer getMember() {
		return this.member;
	}

	public void setMember(Integer member) {
		this.member = member;
	}

	@Column(name = "villa")
	public Integer getVilla() {
		return this.villa;
	}

	public void setVilla(Integer villa) {
		this.villa = villa;
	}

	@Column(name = "order")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
