package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Formula;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "Comment", catalog = "villa")
public class Comment implements java.io.Serializable {

	private Integer id;
	private Integer orderid;
	private Integer villa;
	private Integer star;
	private String content;
	private Date commentDay;
	
	private String memberName;
	private String memberHead;
	
	private Set<Img> img = new HashSet<Img>();
	

	public Comment() {
	}

	public Comment(Integer orderid, Integer star,
			String content, Date commentDay) {
		this.orderid = orderid;
		this.star = star;
		this.content = content;
		this.commentDay = commentDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	@Column(name = "orderid")
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_Day", length = 19)
	public Date getCommentDay() {
		return this.commentDay;
	}

	public void setCommentDay(Date commentDay) {
		this.commentDay = commentDay;
	}
	
	@Formula("(select Member.nickname from (Comment join Orders on Comment.orderid  = Orders.id) join  Member on Orders.member = Member.id where Orders.id = orderid)")
	public String getMemberName() {
		return memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}
	
	@Formula("(select Member.headimgurl from (Comment join Orders on Comment.orderid  = Orders.id) join  Member on Orders.member = Member.id where Orders.id = orderid)")
	public String getMemberHead() {
		return memberHead;
	}

	public void setMemberHead(String memberHead) {
		this.memberHead = memberHead;
	}

	
	
	@JoinTable(name = "CommentImg",
			joinColumns = @JoinColumn(name = "comment",
			referencedColumnName = "id"), 
			inverseJoinColumns = @JoinColumn(name = "img", 
			referencedColumnName = "id",unique=false))
	@ManyToMany(fetch=FetchType.EAGER)
	public Set<Img> getImg() {
		return img;
	}

	public void setImg(Set<Img> img) {
		this.img = img;
	}
	@Column(name = "villa")
	public Integer getVilla() {
		return villa;
	}

	public void setVilla(Integer villa) {
		this.villa = villa;
	}


	
	
	
	
}
