package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CommentImg generated by hbm2java
 */
@Entity
@Table(name = "comment_img", catalog = "villa")
public class CommentImg implements java.io.Serializable {

	private CommentImgId id;

	public CommentImg() {
	}

	public CommentImg(CommentImgId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "comment", column = @Column(name = "comment", nullable = false)),
			@AttributeOverride(name = "img", column = @Column(name = "img", nullable = false)) })
	public CommentImgId getId() {
		return this.id;
	}

	public void setId(CommentImgId id) {
		this.id = id;
	}

}
