package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name = "facility", catalog = "villa")
public class Facility implements java.io.Serializable {

	private Integer id;
	private String content;
	private int type;

	public Facility() {
	}

	public Facility(String content, int type) {
		this.content = content;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "content", length = 45)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", length = 45)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
