package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Formula;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "Store", catalog = "villa")
public class Store implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ownerName;
	private String idCard;
	private Integer gender;
	private Integer age;
	private String address;
	private String mobilephone;
	private String telephone;
	private Integer weight;
	private String genderValue;

	public Store() {
	}

	public Store(String name, String ownerName, String idCard, Integer gender,
			Integer age, String address, String mobilephone, String telephone,
			Integer weight) {
		this.name = name;
		this.ownerName = ownerName;
		this.idCard = idCard;
		this.gender = gender;
		this.age = age;
		this.address = address;
		this.mobilephone = mobilephone;
		this.telephone = telephone;
		this.weight = weight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "owner_name", length = 45)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "id_card", length = 45)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "mobilephone", length = 45)
	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	
	@Formula("(select d.value from Store s join Dictionary d on s.gender = d.code where d.key = 'gender' and s.id = id)")
	public String getGenderValue() {
		return genderValue;
	}

	public void setGenderValue(String genderValue) {
		this.genderValue = genderValue;
	}
	
	

}
