package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VillaFacilityId generated by hbm2java
 */
@Embeddable
public class VillaFacilityId implements java.io.Serializable {

	private int villa;
	private int facility;

	public VillaFacilityId() {
	}

	public VillaFacilityId(int villa, int facility) {
		this.villa = villa;
		this.facility = facility;
	}

	@Column(name = "villa", nullable = false)
	public int getVilla() {
		return this.villa;
	}

	public void setVilla(int villa) {
		this.villa = villa;
	}

	@Column(name = "facility", nullable = false)
	public int getFacility() {
		return this.facility;
	}

	public void setFacility(int facility) {
		this.facility = facility;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VillaFacilityId))
			return false;
		VillaFacilityId castOther = (VillaFacilityId) other;

		return (this.getVilla() == castOther.getVilla())
				&& (this.getFacility() == castOther.getFacility());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVilla();
		result = 37 * result + this.getFacility();
		return result;
	}

}
