package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VillaImgId generated by hbm2java
 */
@Embeddable
public class VillaImgId implements java.io.Serializable {

	private int villa;
	private int img;

	public VillaImgId() {
	}

	public VillaImgId(int villa, int img) {
		this.villa = villa;
		this.img = img;
	}

	@Column(name = "villa", nullable = false)
	public int getVilla() {
		return this.villa;
	}

	public void setVilla(int villa) {
		this.villa = villa;
	}

	@Column(name = "img", nullable = false)
	public int getImg() {
		return this.img;
	}

	public void setImg(int img) {
		this.img = img;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VillaImgId))
			return false;
		VillaImgId castOther = (VillaImgId) other;

		return (this.getVilla() == castOther.getVilla())
				&& (this.getImg() == castOther.getImg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVilla();
		result = 37 * result + this.getImg();
		return result;
	}

}
