package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1



import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Formula;
import org.springframework.transaction.annotation.Transactional;


/**
 * Villa generated by hbm2java
 */
@Entity
@Table(name = "Villa", catalog = "villa")
public class Villa implements java.io.Serializable {

	private Integer id;
	private String province;
	private String city;
	private String district;
	private String detail;
	private Integer store;
	private String name;
	private Integer bedroom;
	private Integer people;
	private Double normalPrice;
	private Double specialPrice;
	private Integer star;
	private String description;
	private Integer weight;
	private String storeName;
	private Set<Svs> svs =new HashSet<Svs>();//(List<Svs>) new HashSet<Svs>();
	private Set<Facility> facility = new HashSet<Facility>();
	private Set<Img> img = new HashSet<Img>();
	private String qrcode;
 	
	
	public Villa() {
	}

	public Villa(String province, String city, String district, String detail,
			Integer store, String name, Integer bedroom, Integer people,
			Double normalPrice, Double specialPrice, Integer star,
			String description, Integer weight) {
		this.province = province;
		this.city = city;
		this.district = district;
		this.detail = detail;
		this.store = store;
		this.name = name;
		this.bedroom = bedroom;
		this.people = people;
		this.normalPrice = normalPrice;
		this.specialPrice = specialPrice;
		this.star = star;
		this.description = description;
		this.weight = weight;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "province", length = 45)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district", length = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "detail", length = 200)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "store")
	public Integer getStore() {
		return this.store;
	}

	public void setStore(Integer store) {
		this.store = store;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "bedroom")
	public Integer getBedroom() {
		return this.bedroom;
	}

	public void setBedroom(Integer bedroom) {
		this.bedroom = bedroom;
	}

	@Column(name = "people")
	public Integer getPeople() {
		return this.people;
	}

	public void setPeople(Integer people) {
		this.people = people;
	}

	@Column(name = "normal_price", precision = 22, scale = 0)
	public Double getNormalPrice() {
		return this.normalPrice;
	}

	public void setNormalPrice(Double normalPrice) {
		this.normalPrice = normalPrice;
	}

	@Column(name = "special_price", precision = 22, scale = 0)
	public Double getSpecialPrice() {
		return this.specialPrice;
	}

	public void setSpecialPrice(Double specialPrice) {
		this.specialPrice = specialPrice;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	
	@Formula("(SELECT s.name FROM Store s WHERE s.id = store )")
	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@JoinTable(name = "VillaSvs",
			// 定义连接表中名为person_id的外键列，该外键列参照当前实体对应表的主键列
			joinColumns = @JoinColumn(name = "villa",
			// 定义连接表中名为address_id的外键列，
			// 该外键列参照当前实体的关联实体对应表的主键列，没有指定unique=true
			referencedColumnName = "id"), 
			inverseJoinColumns = @JoinColumn(name = "svs", 
			referencedColumnName = "id",unique=false))
	//@ElementCollection
	@ManyToMany(fetch=FetchType.EAGER)
	public Set<Svs> getSvs() {
		return svs;
	}

	public void setSvs(Set<Svs> svs) {
		this.svs = svs;
	}
	@JoinTable(name = "VillaFacility",
			joinColumns = @JoinColumn(name = "villa",
			referencedColumnName = "id"), 
			inverseJoinColumns = @JoinColumn(name = "facility", 
			referencedColumnName = "id",unique=false))
	@ManyToMany(fetch=FetchType.EAGER)
	public Set<Facility> getFacility() {
		return facility;
	}

	public void setFacility(Set<Facility> facility) {
		this.facility = facility;
	}
	@JoinTable(name = "VillaImg",
			joinColumns = @JoinColumn(name = "villa",
			referencedColumnName = "id"), 
			inverseJoinColumns = @JoinColumn(name = "img", 
			referencedColumnName = "id",unique=false))
	@ManyToMany(fetch=FetchType.EAGER)
	public Set<Img> getImg() {
		return img;
	}

	public void setImg(Set<Img> img) {
		this.img = img;
	}

	@Transient
	public String getQrcode() {
		return qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}


	
}
