package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VillaImg generated by hbm2java
 */
@Entity
@Table(name = "villa_img", catalog = "villa")
public class VillaImg implements java.io.Serializable {

	private VillaImgId id;

	public VillaImg() {
	}

	public VillaImg(VillaImgId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "villa", column = @Column(name = "villa", nullable = false)),
			@AttributeOverride(name = "img", column = @Column(name = "img", nullable = false)) })
	public VillaImgId getId() {
		return this.id;
	}

	public void setId(VillaImgId id) {
		this.id = id;
	}

}
