package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VillaImg generated by hbm2java
 */
@Entity
@Table(name = "VillaImg", catalog = "villa")
public class VillaImg implements java.io.Serializable {

	private Integer id;
	private Integer villa;
	private Integer img;

	public VillaImg() {
	}

	public VillaImg(Integer villa, Integer img) {
		this.villa = villa;
		this.img = img;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "villa")
	public Integer getVilla() {
		return this.villa;
	}

	public void setVilla(Integer villa) {
		this.villa = villa;
	}

	@Column(name = "img")
	public Integer getImg() {
		return this.img;
	}

	public void setImg(Integer img) {
		this.img = img;
	}

}
