package com.zjlh.villa.entity;

// Generated 2015-8-8 15:38:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VillaSvs generated by hbm2java
 */
@Entity
@Table(name = "VillaSvs", catalog = "villa")
public class VillaSvs implements java.io.Serializable {

	private Integer id;
	private Integer villa;
	private Integer svs;

	public VillaSvs() {
	}

	public VillaSvs(Integer villa, Integer svs) {
		this.villa = villa;
		this.svs = svs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "villa")
	public Integer getVilla() {
		return this.villa;
	}

	public void setVilla(Integer villa) {
		this.villa = villa;
	}

	@Column(name = "svs")
	public Integer getSvs() {
		return this.svs;
	}

	public void setSvs(Integer svs) {
		this.svs = svs;
	}

}
