package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VillaServiceId generated by hbm2java
 */
@Embeddable
public class VillaServiceId implements java.io.Serializable {

	private int villa;
	private int service;

	public VillaServiceId() {
	}

	public VillaServiceId(int villa, int service) {
		this.villa = villa;
		this.service = service;
	}

	@Column(name = "villa", nullable = false)
	public int getVilla() {
		return this.villa;
	}

	public void setVilla(int villa) {
		this.villa = villa;
	}

	@Column(name = "service", nullable = false)
	public int getService() {
		return this.service;
	}

	public void setService(int service) {
		this.service = service;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VillaServiceId))
			return false;
		VillaServiceId castOther = (VillaServiceId) other;

		return (this.getVilla() == castOther.getVilla())
				&& (this.getService() == castOther.getService());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVilla();
		result = 37 * result + this.getService();
		return result;
	}

}
