package com.zjlh.villa.entity;

// Generated 2015-8-5 20:46:39 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VillaService generated by hbm2java
 */
@Entity
@Table(name = "villa_service", catalog = "villa")
public class VillaService implements java.io.Serializable {

	private VillaServiceId id;

	public VillaService() {
	}

	public VillaService(VillaServiceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "villa", column = @Column(name = "villa", nullable = false)),
			@AttributeOverride(name = "service", column = @Column(name = "service", nullable = false)) })
	public VillaServiceId getId() {
		return this.id;
	}

	public void setId(VillaServiceId id) {
		this.id = id;
	}

}
